project:
  type: website
  output-dir: docs

website:
  title: "ArkSena"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: demo.qmd
        text: Graphic Demo
      - href: photogrametry.qmd
        text: Photogrametry
  page-footer: "© 2026 Mathys Carboila Dias | Built with Quarto & Three.js"
  search: false

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: content/style/styles.css
    toc: true

execute:
  freeze: auto

# Configuration for GitHub Pages
publish:
  provider: "github"
  branch: "main"
